In [30]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [35]:
class SVM:
    
    def __init__(self,learning_rate=0.001,lambda_param=0.01,n_iters=1000):
        self.lr = learning_rate
        self.lambda_param = lambda_param
        self.n_iters = n_iters
        self.w = None
        self.b = None
        
    def fit(self,X,y):
        y_ = np.where(y <= 0,-1,1) # converts all the y less than or equal to 0 to -1 and others to 1
        n_samples, n_features = X.shape
        
        self.w = np.zeros(n_features)
        self.b = 0

        for _ in range(self.n_iters):
            for idx, x_i in enumerate(X):
                condition = y_[idx] * (np.dot(x_i,self.w)-self.b) >= 1
                
                if condition:
#                     dw = 2*self.lambda_param*self.w
#                     db = 0
                    self.w -= self.lr*(2*self.lambda_param*self.w)
                else:
                    self.w -= self.lr*(2*self.lambda_param*self.w-np.dot(x_i,y_[idx]))
                    self.b -= self.lr*y_[idx]
                    
    
    def predict(self,X):
        linear_output = np.dot(X,self.w) - self.b
        return = np.sign(linear_output) # converts all the linear_output to -1 if less than 0, 0 if 0 and 1 if more than 0
    
        
        
    

SyntaxError: invalid syntax (Temp/ipykernel_15400/431122424.py, line 32)

In [36]:
class SVM:
    def __init__(self, learning_rate=0.001, lambda_param=0.01, n_iters=1000):
        self.lr = learning_rate
        self.lambda_param = lambda_param
        self.n_iters = n_iters
        self.w = None
        self.b = None

    def fit(self, X, y):
        n_samples, n_features = X.shape

        y_ = np.where(y <= 0, -1, 1)

        self.w = np.zeros(n_features)
        self.b = 0

        for _ in range(self.n_iters):
            for idx, x_i in enumerate(X):
                condition = y_[idx] * (np.dot(x_i, self.w) - self.b) >= 1
                if condition:
                    self.w -= self.lr * (2 * self.lambda_param * self.w)
                else:
                    self.w -= self.lr * (
                        2 * self.lambda_param * self.w - np.dot(x_i, y_[idx])
                    )
                    self.b -= self.lr * y_[idx]

    def predict(self, X):
        approx = np.dot(X, self.w) - self.b
        return np.sign(approx)

In [37]:
X, y = datasets.make_blobs(n_samples=50,n_features=2,centers=2,cluster_std=1.05,random_state=40)
y = np.where(y==0,-1,1)

In [38]:
clf = SVM()
clf.fit(X,y)

In [4]:
np.sign([10,30,-12,0 ])

array([ 1,  1, -1,  0])

In [10]:
np.where(np.arange(9).reshape((3,3))<4,0,100)

array([[  0,   0,   0],
       [  0, 100, 100],
       [100, 100, 100]])

In [15]:
a=np.array([10,30,-12,0])
print(np.where((a < 2) & (a < 6) | (a == 7), -1, 100))


[100 100  -1  -1]


In [16]:
a = np.arange(5)
b = np.arange(1,6)

In [17]:
a 

array([0, 1, 2, 3, 4])

In [18]:
b

array([1, 2, 3, 4, 5])

In [19]:
np.dot(a,b)

40

In [20]:
np.inner(a,b)

40

In [21]:
np.dot(b,a)

40

In [22]:
np.inner(b,a)

40

In [26]:
np.zeros(10).shape

(10,)

In [1]:
import cvxpy as cp 